OnlineShopApp/Models/Comparison.cs
namespace OnlineShopApp.Models
{
    public class Comparison
    {
        public Guid Id { get; set; }
        public string UserId { get; set; }
        public List<Product> Items { get; set; }
    }
}

OnlineShopApp/Controllers/ComparisonController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShopApp.Interfaces;

namespace OnlineShopApp.Controllers
{
    public class ComparisonController : Controller
    {
        private readonly IComparisonRepository _comparisonRepository;
        private readonly IProductsRepository _productsRepository;

        public ComparisonController(IComparisonRepository comparisonRepository, IProductsRepository productsRepository)
        {
            _comparisonRepository = comparisonRepository;
            _productsRepository = productsRepository;
        }

        public IActionResult Index()
        {
            var comparison = _comparisonRepository.TryGetByUserId(Constans.UserId);

            return View(comparison);
        }

        public IActionResult Add(int productId)
        {
            var product = _productsRepository.TryGetById(productId);
            if (product is not null)
            {
                _comparisonRepository.Add(product, Constans.UserId);
            }
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Delete(int productId)
        {
            _comparisonRepository.Delete(productId, Constans.UserId);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Clear()
        {
            _comparisonRepository.Clear(Constans.UserId);

            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShopApp/Views/Comparison/Index.cshtml
@model Comparison
@{
    ViewData["Title"] = "Сравнение товаров";
}

<div class="text-center text-uppercase text-success mb-5 mt-5">
    <h2 class="row-title">Сравнение товаров</h2>
</div>

@if (Model != null && Model.Items?.Count > 0)
{
    <div class="row justify-content-center mt-3">
        @foreach (var product in Model.Items)
        {
            <div class="col-3 mb-3">
                <div class="card shadow">
                    <img class="card-img-top" src="@product.PhotoPath" alt="...">
                    <div class="card-body text-center">
                        <a class="text-success"
                           asp-controller="Product"
                           asp-action="Index"
                           asp-route-id="@product.Id">
                            <h5>@product.Name</h5>
                        </a>
                        <h2 class="text-danger">@product.Cost.ToString("c")</h2>
                        <a class="btn btn-success"
                           asp-controller="Cart"
                           asp-action="Add"
                           asp-route-productId="@product.Id">
                            Добавить в корзину
                        </a>
                        <a class="btn btn-outline-danger mt-3"
                           asp-controller="Comparison"
                           asp-action="Delete"
                           asp-route-productId="@product.Id">
                            Убрать из сравнения
                        </a>
                    </div>
                </div>
            </div>
        }

        <div class="text-center mt-5">
            <a class="btn btn-outline-danger"
               asp-controller="Comparison"
               asp-action="Clear">
                Очистить список сравнения
            </a>
        </div>
    </div>
}
else
{
    <div class="text-center">
        <h2 class="row-title">В списке сравнения нет товаров!</h2>
    </div>

}

<div class="text-center m-5">
    <a class="btn btn-outline-success"
       asp-controller="Home"
       asp-action="Index">
        Продолжить покупки
    </a>
</div>